export const cfg = {
	NEXT_PUBLIC_BASE_URL_APIS_PERU: process.env.NEXT_PUBLIC_BASE_URL_APIS_PERU,
	NEXT_PUBLIC_TOKEN_APIS_PERU: process.env.NEXT_PUBLIC_TOKEN_APIS_PERU,
	NEXT_PUBLIC_SUPABASE_BASE_URL: process.env.NEXT_PUBLIC_SUPABASE_BASE_URL,
	NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
}
